var exampleWeatherData = {
  "Transfer-Encoding": "chunked",
  "Connection": "keep-alive",
  "Vary": "Accept-Encoding",
  "CDN-PullZone": "93447",
  "CDN-Uid": "8fa3a04a-75d9-4707-8056-b7b33c8ac7fe",
  "CDN-RequestCountryCode": "GB",
  "CDN-ProxyVer": "1.02",
  "CDN-RequestPullSuccess": "True",
  "CDN-RequestPullCode": "200",
  "CDN-CachedAt": "09/24/2022 23:20:52",
  "CDN-EdgeStorageId": "946",
  "CDN-Status": "200",
  "CDN-RequestId": "c11cd0b550b6838a08e00baf7fd187cc",
  "CDN-Cache": "HIT",
  "Cache-Control": "public, max-age=180",
  "Content-Type": "application/json",
  "Date": "Sat, 24 Sep 2022 23:20:53 GMT",
  "Server": "BunnyCDN-FR-951"
}
Response Body
{
    "location": {
        "name": "Austin",
        "region": "Texas",
        "country": "United States of America",
        "lat": 30.27,
        "lon": -97.74,
        "tz_id": "America/Chicago",
        "localtime_epoch": 1664061652,
        "localtime": "2022-09-24 18:20"
    },
    "current": {
        "last_updated_epoch": 1664061300,
        "last_updated": "2022-09-24 18:15",
        "temp_c": 32.2,
        "temp_f": 90.0,
        "is_day": 1,
        "condition": {
            "text": "Partly cloudy",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
            "code": 1003
        },
        "wind_mph": 11.9,
        "wind_kph": 19.1,
        "wind_degree": 150,
        "wind_dir": "SSE",
        "pressure_mb": 1013.0,
        "pressure_in": 29.92,
        "precip_mm": 0.0,
        "precip_in": 0.0,
        "humidity": 47,
        "cloud": 50,
        "feelslike_c": 33.0,
        "feelslike_f": 91.4,
        "vis_km": 16.0,
        "vis_miles": 9.0,
        "uv": 9.0,
        "gust_mph": 15.2,
        "gust_kph": 24.5,
        "air_quality": {
            "co": 210.3000030517578,
            "no2": 4.800000190734863,
            "o3": 100.0999984741211,
            "so2": 0.699999988079071,
            "pm2_5": 4.0,
            "pm10": 6.099999904632568,
            "us-epa-index": 1,
            "gb-defra-index": 1
        }
    },
    "forecast": {
        "forecastday": [
            {
                "date": "2022-09-24",
                "date_epoch": 1663977600,
                "day": {
                    "maxtemp_c": 37.0,
                    "maxtemp_f": 98.6,
                    "mintemp_c": 22.4,
                    "mintemp_f": 72.3,
                    "avgtemp_c": 29.6,
                    "avgtemp_f": 85.3,
                    "maxwind_mph": 13.2,
                    "maxwind_kph": 21.2,
                    "totalprecip_mm": 0.0,
                    "totalprecip_in": 0.0,
                    "avgvis_km": 10.0,
                    "avgvis_miles": 6.0,
                    "avghumidity": 60.0,
                    "daily_will_it_rain": 0,
                    "daily_chance_of_rain": 0,
                    "daily_will_it_snow": 0,
                    "daily_chance_of_snow": 0,
                    "condition": {
                        "text": "Sunny",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                        "code": 1000
                    },
                    "uv": 7.0
                },
                "astro": {
                    "sunrise": "07:21 AM",
                    "sunset": "07:25 PM",
                    "moonrise": "06:03 AM",
                    "moonset": "07:06 PM",
                    "moon_phase": "New Moon",
                    "moon_illumination": "0"
                },
                "hour": [
                    {
                        "time_epoch": 1663995600,
                        "time": "2022-09-24 00:00",
                        "temp_c": 28.6,
                        "temp_f": 83.5,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 10.7,
                        "wind_kph": 17.3,
                        "wind_degree": 180,
                        "wind_dir": "S",
                        "pressure_mb": 1015.0,
                        "pressure_in": 29.97,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 55,
                        "cloud": 0,
                        "feelslike_c": 30.1,
                        "feelslike_f": 86.2,
                        "windchill_c": 28.6,
                        "windchill_f": 83.5,
                        "heatindex_c": 30.1,
                        "heatindex_f": 86.2,
                        "dewpoint_c": 18.7,
                        "dewpoint_f": 65.7,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 14.1,
                        "gust_kph": 22.7,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1663999200,
                        "time": "2022-09-24 01:00",
                        "temp_c": 27.1,
                        "temp_f": 80.8,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 9.4,
                        "wind_kph": 15.1,
                        "wind_degree": 184,
                        "wind_dir": "S",
                        "pressure_mb": 1015.0,
                        "pressure_in": 29.98,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 63,
                        "cloud": 0,
                        "feelslike_c": 28.8,
                        "feelslike_f": 83.8,
                        "windchill_c": 27.1,
                        "windchill_f": 80.8,
                        "heatindex_c": 28.8,
                        "heatindex_f": 83.8,
                        "dewpoint_c": 19.5,
                        "dewpoint_f": 67.1,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 13.0,
                        "gust_kph": 20.9,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1664002800,
                        "time": "2022-09-24 02:00",
                        "temp_c": 26.0,
                        "temp_f": 78.8,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 8.3,
                        "wind_kph": 13.3,
                        "wind_degree": 186,
                        "wind_dir": "S",
                        "pressure_mb": 1016.0,
                        "pressure_in": 30.0,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 68,
                        "cloud": 0,
                        "feelslike_c": 27.7,
                        "feelslike_f": 81.9,
                        "windchill_c": 26.0,
                        "windchill_f": 78.8,
                        "heatindex_c": 27.7,
                        "heatindex_f": 81.9,
                        "dewpoint_c": 19.7,
                        "dewpoint_f": 67.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 11.9,
                        "gust_kph": 19.1,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1664006400,
                        "time": "2022-09-24 03:00",
                        "temp_c": 25.2,
                        "temp_f": 77.4,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 7.8,
                        "wind_kph": 12.6,
                        "wind_degree": 189,
                        "wind_dir": "S",
                        "pressure_mb": 1016.0,
                        "pressure_in": 30.0,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 72,
                        "cloud": 0,
                        "feelslike_c": 26.9,
                        "feelslike_f": 80.4,
                        "windchill_c": 25.2,
                        "windchill_f": 77.4,
                        "heatindex_c": 26.9,
                        "heatindex_f": 80.4,
                        "dewpoint_c": 19.8,
                        "dewpoint_f": 67.6,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 11.4,
                        "gust_kph": 18.4,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1664010000,
                        "time": "2022-09-24 04:00",
                        "temp_c": 24.0,
                        "temp_f": 75.2,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 6.7,
                        "wind_kph": 10.8,
                        "wind_degree": 189,
                        "wind_dir": "S",
                        "pressure_mb": 1016.0,
                        "pressure_in": 30.0,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 77,
                        "cloud": 0,
                        "feelslike_c": 25.8,
                        "feelslike_f": 78.4,
                        "windchill_c": 24.0,
                        "windchill_f": 75.2,
                        "heatindex_c": 25.8,
                        "heatindex_f": 78.4,
                        "dewpoint_c": 19.7,
                        "dewpoint_f": 67.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 9.6,
                        "gust_kph": 15.5,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1664013600,
                        "time": "2022-09-24 05:00",
                        "temp_c": 23.3,
                        "temp_f": 73.9,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 6.0,
                        "wind_kph": 9.7,
                        "wind_degree": 187,
                        "wind_dir": "S",
                        "pressure_mb": 1016.0,
                        "pressure_in": 29.99,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 78,
                        "cloud": 0,
                        "feelslike_c": 25.3,
                        "feelslike_f": 77.5,
                        "windchill_c": 23.3,
                        "windchill_f": 73.9,
                        "heatindex_c": 25.3,
                        "heatindex_f": 77.5,
                        "dewpoint_c": 19.3,
                        "dewpoint_f": 66.7,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 9.2,
                        "gust_kph": 14.8,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1664017200,
                        "time": "2022-09-24 06:00",
                        "temp_c": 22.9,
                        "temp_f": 73.2,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 5.8,
                        "wind_kph": 9.4,
                        "wind_degree": 188,
                        "wind_dir": "S",
                        "pressure_mb": 1016.0,
                        "pressure_in": 30.01,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 80,
                        "cloud": 1,
                        "feelslike_c": 25.0,
                        "feelslike_f": 77.0,
                        "windchill_c": 22.9,
                        "windchill_f": 73.2,
                        "heatindex_c": 25.0,
                        "heatindex_f": 77.0,
                        "dewpoint_c": 19.2,
                        "dewpoint_f": 66.6,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 8.9,
                        "gust_kph": 14.4,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1664020800,
                        "time": "2022-09-24 07:00",
                        "temp_c": 22.4,
                        "temp_f": 72.3,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 4.9,
                        "wind_kph": 7.9,
                        "wind_degree": 192,
                        "wind_dir": "SSW",
                        "pressure_mb": 1017.0,
                        "pressure_in": 30.02,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 82,
                        "cloud": 20,
                        "feelslike_c": 24.7,
                        "feelslike_f": 76.5,
                        "windchill_c": 22.4,
                        "windchill_f": 72.3,
                        "heatindex_c": 24.7,
                        "heatindex_f": 76.5,
                        "dewpoint_c": 19.2,
                        "dewpoint_f": 66.6,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 7.6,
                        "gust_kph": 12.2,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1664024400,
                        "time": "2022-09-24 08:00",
                        "temp_c": 23.0,
                        "temp_f": 73.4,
                        "is_day": 1,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            "code": 1003
                        },
                        "wind_mph": 4.5,
                        "wind_kph": 7.2,
                        "wind_degree": 191,
                        "wind_dir": "SSW",
                        "pressure_mb": 1017.0,
                        "pressure_in": 30.03,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 79,
                        "cloud": 37,
                        "feelslike_c": 25.1,
                        "feelslike_f": 77.2,
                        "windchill_c": 23.0,
                        "windchill_f": 73.4,
                        "heatindex_c": 25.1,
                        "heatindex_f": 77.2,
                        "dewpoint_c": 19.1,
                        "dewpoint_f": 66.4,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 6.0,
                        "gust_kph": 9.7,
                        "uv": 6.0
                    },
                    {
                        "time_epoch": 1664028000,
                        "time": "2022-09-24 09:00",
                        "temp_c": 25.4,
                        "temp_f": 77.7,
                        "is_day": 1,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            "code": 1003
                        },
                        "wind_mph": 5.4,
                        "wind_kph": 8.6,
                        "wind_degree": 186,
                        "wind_dir": "S",
                        "pressure_mb": 1018.0,
                        "pressure_in": 30.05,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 75,
                        "cloud": 38,
                        "feelslike_c": 27.3,
                        "feelslike_f": 81.1,
                        "windchill_c": 25.4,
                        "windchill_f": 77.7,
                        "heatindex_c": 27.3,
                        "heatindex_f": 81.1,
                        "dewpoint_c": 20.6,
                        "dewpoint_f": 69.1,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 6.3,
                        "gust_kph": 10.1,
                        "uv": 7.0
                    },
                    {
                        "time_epoch": 1664031600,
                        "time": "2022-09-24 10:00",
                        "temp_c": 27.6,
                        "temp_f": 81.7,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 5.6,
                        "wind_kph": 9.0,
                        "wind_degree": 185,
                        "wind_dir": "S",
                        "pressure_mb": 1017.0,
                        "pressure_in": 30.03,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 64,
                        "cloud": 0,
                        "feelslike_c": 29.6,
                        "feelslike_f": 85.3,
                        "windchill_c": 27.6,
                        "windchill_f": 81.7,
                        "heatindex_c": 29.6,
                        "heatindex_f": 85.3,
                        "dewpoint_c": 20.3,
                        "dewpoint_f": 68.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 6.5,
                        "gust_kph": 10.4,
                        "uv": 7.0
                    },
                    {
                        "time_epoch": 1664035200,
                        "time": "2022-09-24 11:00",
                        "temp_c": 32.6,
                        "temp_f": 90.7,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 6.7,
                        "wind_kph": 10.8,
                        "wind_degree": 175,
                        "wind_dir": "S",
                        "pressure_mb": 1017.0,
                        "pressure_in": 30.03,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 57,
                        "cloud": 3,
                        "feelslike_c": 37.7,
                        "feelslike_f": 99.9,
                        "windchill_c": 32.6,
                        "windchill_f": 90.7,
                        "heatindex_c": 37.7,
                        "heatindex_f": 99.9,
                        "dewpoint_c": 22.9,
                        "dewpoint_f": 73.2,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 7.8,
                        "gust_kph": 12.6,
                        "uv": 8.0
                    },
                    {
                        "time_epoch": 1664038800,
                        "time": "2022-09-24 12:00",
                        "temp_c": 34.3,
                        "temp_f": 93.7,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 7.6,
                        "wind_kph": 12.2,
                        "wind_degree": 171,
                        "wind_dir": "S",
                        "pressure_mb": 1017.0,
                        "pressure_in": 30.02,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 51,
                        "cloud": 0,
                        "feelslike_c": 39.9,
                        "feelslike_f": 103.8,
                        "windchill_c": 34.3,
                        "windchill_f": 93.7,
                        "heatindex_c": 39.9,
                        "heatindex_f": 103.8,
                        "dewpoint_c": 22.7,
                        "dewpoint_f": 72.9,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 8.7,
                        "gust_kph": 14.0,
                        "uv": 8.0
                    },
                    {
                        "time_epoch": 1664042400,
                        "time": "2022-09-24 13:00",
                        "temp_c": 35.4,
                        "temp_f": 95.7,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 8.7,
                        "wind_kph": 14.0,
                        "wind_degree": 175,
                        "wind_dir": "S",
                        "pressure_mb": 1015.0,
                        "pressure_in": 29.98,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 46,
                        "cloud": 0,
                        "feelslike_c": 40.7,
                        "feelslike_f": 105.3,
                        "windchill_c": 35.4,
                        "windchill_f": 95.7,
                        "heatindex_c": 40.7,
                        "heatindex_f": 105.3,
                        "dewpoint_c": 22.0,
                        "dewpoint_f": 71.6,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 10.1,
                        "gust_kph": 16.2,
                        "uv": 9.0
                    },
                    {
                        "time_epoch": 1664046000,
                        "time": "2022-09-24 14:00",
                        "temp_c": 36.3,
                        "temp_f": 97.3,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 9.4,
                        "wind_kph": 15.1,
                        "wind_degree": 176,
                        "wind_dir": "S",
                        "pressure_mb": 1015.0,
                        "pressure_in": 29.96,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 43,
                        "cloud": 0,
                        "feelslike_c": 41.5,
                        "feelslike_f": 106.7,
                        "windchill_c": 36.3,
                        "windchill_f": 97.3,
                        "heatindex_c": 41.5,
                        "heatindex_f": 106.7,
                        "dewpoint_c": 21.6,
                        "dewpoint_f": 70.9,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 10.7,
                        "gust_kph": 17.3,
                        "uv": 9.0
                    },
                    {
                        "time_epoch": 1664049600,
                        "time": "2022-09-24 15:00",
                        "temp_c": 37.0,
                        "temp_f": 98.6,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 8.5,
                        "wind_kph": 13.7,
                        "wind_degree": 173,
                        "wind_dir": "S",
                        "pressure_mb": 1014.0,
                        "pressure_in": 29.94,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 40,
                        "cloud": 0,
                        "feelslike_c": 42.0,
                        "feelslike_f": 107.6,
                        "windchill_c": 37.0,
                        "windchill_f": 98.6,
                        "heatindex_c": 42.0,
                        "heatindex_f": 107.6,
                        "dewpoint_c": 21.1,
                        "dewpoint_f": 70.0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 9.8,
                        "gust_kph": 15.8,
                        "uv": 9.0
                    },
                    {
                        "time_epoch": 1664053200,
                        "time": "2022-09-24 16:00",
                        "temp_c": 36.7,
                        "temp_f": 98.1,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 9.8,
                        "wind_kph": 15.8,
                        "wind_degree": 185,
                        "wind_dir": "S",
                        "pressure_mb": 1013.0,
                        "pressure_in": 29.91,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 39,
                        "cloud": 0,
                        "feelslike_c": 40.9,
                        "feelslike_f": 105.6,
                        "windchill_c": 36.7,
                        "windchill_f": 98.1,
                        "heatindex_c": 40.9,
                        "heatindex_f": 105.6,
                        "dewpoint_c": 20.4,
                        "dewpoint_f": 68.7,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 11.4,
                        "gust_kph": 18.4,
                        "uv": 9.0
                    },
                    {
                        "time_epoch": 1664056800,
                        "time": "2022-09-24 17:00",
                        "temp_c": 36.1,
                        "temp_f": 97.0,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 13.2,
                        "wind_kph": 21.2,
                        "wind_degree": 212,
                        "wind_dir": "SSW",
                        "pressure_mb": 1012.0,
                        "pressure_in": 29.89,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 39,
                        "cloud": 3,
                        "feelslike_c": 39.7,
                        "feelslike_f": 103.5,
                        "windchill_c": 36.1,
                        "windchill_f": 97.0,
                        "heatindex_c": 39.7,
                        "heatindex_f": 103.5,
                        "dewpoint_c": 19.9,
                        "dewpoint_f": 67.8,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 15.2,
                        "gust_kph": 24.5,
                        "uv": 9.0
                    },
                    {
                        "time_epoch": 1664060400,
                        "time": "2022-09-24 18:00",
                        "temp_c": 35.0,
                        "temp_f": 95.0,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 10.7,
                        "wind_kph": 17.3,
                        "wind_degree": 189,
                        "wind_dir": "S",
                        "pressure_mb": 1012.0,
                        "pressure_in": 29.89,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 41,
                        "cloud": 11,
                        "feelslike_c": 38.2,
                        "feelslike_f": 100.8,
                        "windchill_c": 35.0,
                        "windchill_f": 95.0,
                        "heatindex_c": 38.2,
                        "heatindex_f": 100.8,
                        "dewpoint_c": 19.7,
                        "dewpoint_f": 67.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 12.3,
                        "gust_kph": 19.8,
                        "uv": 9.0
                    },
                    {
                        "time_epoch": 1664064000,
                        "time": "2022-09-24 19:00",
                        "temp_c": 33.2,
                        "temp_f": 91.8,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 11.2,
                        "wind_kph": 18.0,
                        "wind_degree": 162,
                        "wind_dir": "SSE",
                        "pressure_mb": 1012.0,
                        "pressure_in": 29.89,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 46,
                        "cloud": 1,
                        "feelslike_c": 36.1,
                        "feelslike_f": 97.0,
                        "windchill_c": 33.2,
                        "windchill_f": 91.8,
                        "heatindex_c": 36.1,
                        "heatindex_f": 97.0,
                        "dewpoint_c": 19.9,
                        "dewpoint_f": 67.8,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 13.0,
                        "gust_kph": 20.9,
                        "uv": 8.0
                    },
                    {
                        "time_epoch": 1664067600,
                        "time": "2022-09-24 20:00",
                        "temp_c": 31.2,
                        "temp_f": 88.2,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 7.4,
                        "wind_kph": 11.9,
                        "wind_degree": 172,
                        "wind_dir": "S",
                        "pressure_mb": 1013.0,
                        "pressure_in": 29.9,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 53,
                        "cloud": 0,
                        "feelslike_c": 33.9,
                        "feelslike_f": 93.0,
                        "windchill_c": 31.2,
                        "windchill_f": 88.2,
                        "heatindex_c": 33.9,
                        "heatindex_f": 93.0,
                        "dewpoint_c": 20.3,
                        "dewpoint_f": 68.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 9.6,
                        "gust_kph": 15.5,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1664071200,
                        "time": "2022-09-24 21:00",
                        "temp_c": 30.1,
                        "temp_f": 86.2,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 6.3,
                        "wind_kph": 10.1,
                        "wind_degree": 180,
                        "wind_dir": "S",
                        "pressure_mb": 1013.0,
                        "pressure_in": 29.92,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 58,
                        "cloud": 0,
                        "feelslike_c": 32.9,
                        "feelslike_f": 91.2,
                        "windchill_c": 30.1,
                        "windchill_f": 86.2,
                        "heatindex_c": 32.9,
                        "heatindex_f": 91.2,
                        "dewpoint_c": 20.9,
                        "dewpoint_f": 69.6,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 8.5,
                        "gust_kph": 13.7,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1664074800,
                        "time": "2022-09-24 22:00",
                        "temp_c": 29.2,
                        "temp_f": 84.6,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 9.6,
                        "wind_kph": 15.5,
                        "wind_degree": 177,
                        "wind_dir": "S",
                        "pressure_mb": 1014.0,
                        "pressure_in": 29.93,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 62,
                        "cloud": 0,
                        "feelslike_c": 31.9,
                        "feelslike_f": 89.4,
                        "windchill_c": 29.2,
                        "windchill_f": 84.6,
                        "heatindex_c": 31.9,
                        "heatindex_f": 89.4,
                        "dewpoint_c": 21.1,
                        "dewpoint_f": 70.0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 11.9,
                        "gust_kph": 19.1,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1664078400,
                        "time": "2022-09-24 23:00",
                        "temp_c": 28.5,
                        "temp_f": 83.3,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 11.0,
                        "wind_kph": 17.6,
                        "wind_degree": 172,
                        "wind_dir": "S",
                        "pressure_mb": 1014.0,
                        "pressure_in": 29.93,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 66,
                        "cloud": 0,
                        "feelslike_c": 31.2,
                        "feelslike_f": 88.2,
                        "windchill_c": 28.5,
                        "windchill_f": 83.3,
                        "heatindex_c": 31.2,
                        "heatindex_f": 88.2,
                        "dewpoint_c": 21.4,
                        "dewpoint_f": 70.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 13.4,
                        "gust_kph": 21.6,
                        "uv": 1.0
                    }
                ]
            }
        ]
    }
}

export default exampleWeatherData;